### PR TITLE
annotate errors

### PR DESCRIPTION
**Pull request by Stebalien**
See: https://github.com/libp2p/go-libp2p-kad-dht/issues/221

### CODE REVIEW

**Comment by anacrolix** [comment]
I recommend using https://godoc.org/github.com/pkg/errors#Wrap instead.

**Comment by Stebalien** [comment]
@anacrolix maybe... It looks like that package records a stack trace. Generating stack traces for errors can get a bit expensive. We'd have to carefully profile that before using it.

Ideally, it would provide an option to disable collecting stacks. I wonder if they'll accept a PR.

**Comment by anacrolix** [comment]
The `errors.WithMessage` function handles that.

**Comment by Stebalien** [comment]
I see. However, it still adds stack traces by default everywhere else. If we're going to pick a third-party errors library (we should, IMO), I'd like to use it everywhere for. Otherwise, nice features like `Cause` aren't very useful.

**Pull request merged**
